language: node_js

addons:
  ssh_known_hosts:
  - trezy.com

cache: yarn

script:
- yarn run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_12b7f24adab4_key -iv $encrypted_12b7f24adab4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis-deployment@trezy.com:/var/www/rollforguild.com/
  on:
    branch: develop