export default {
  CONFIRM_ACCOUNT: 'CONFIRM_ACCOUNT',
  CREATE_CHARACTER: 'CREATE_CHARACTER',
  GET_CHARACTER: 'GET_CHARACTER',
  GET_CHARACTERS: 'GET_CHARACTERS',
  GET_RULESET: 'GET_RULESET',
  GET_RULESETS: 'GET_RULESETS',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
}
