defaults: &defaults
  docker:
    - image: node:9

  working_directory: ~/repo





jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  install-dependencies:
    <<: *defaults

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build

      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .next

  test:
    <<: *defaults

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-build-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: yarn test

  # pre-deploy:
  #   <<: *defaults

  #   steps:
  #     - add_ssh_keys

  #     - run:
  #         name: Keyscan (HACK)
  #         command: ssh-keyscan -H $DEV_DEPLOY_HOST >> ~/.ssh/known_hosts

  #     - run:
  #         name: Install rsync
  #         command: sudo apt-get update -qq && sudo apt-get install -y rsync

  # dev-deploy:
  #   <<: *defaults

  #   steps:
  #     - run:
  #         name: Deploy to dev.rollforguild.com
  #         command: rsync -r --delete-after --quiet ~/repo/ $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST:$DEV_DEPLOY_FOLDER

  # prod-deploy:
  #   <<: *defaults

  #   steps:
  #     - run:
  #         name: Deploy to rollforguild.com
  #         command: rsync -r --delete-after --quiet ~/repo/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_FOLDER





workflows:
  version: 2

  deploy-to-dev:
    jobs:
      - checkout
      - install-dependencies:
          requires:
            - checkout
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build
      # - dev-deploy:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: develop
      # - prod-deploy:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master
