defaults: &defaults
  docker:
    - image: circleci/node:9.2

  working_directory: /tmp/rollforguild.com

version: 2

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build

  dev-deploy:
    <<: *defaults

    steps:
      # - run:
      #     name: Install some System dependencies
      #     command: sudo apt-get update -qq && sudo apt-get install -y ssh rsync

      - run:
          name: Deploy to dev.rollforguild.com
          command: |
            touch ~/.ssh/known_hosts;
            ssh-keyscan -H $DEV_DEPLOY_HOST >> ~/.ssh/known_hosts;
            rsync -r --delete-after --quiet /tmp/rollforguild.com/ $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST:$DEV_DEPLOY_FOLDER;

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - dev-deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
