// Module imports
import React from 'react'





// Component imports
import Main from '../components/Main'
import Page from '../components/Page'
import PageHeader from '../components/PageHeader'
import PageTitle from '../components/PageTitle'





// Component constants
const title = 'Privacy Policy'





const PrivacyPolicy = () => (
  <React.Fragment>
    <PageTitle>{title}</PageTitle>

    <PageHeader>
      <h1>{title}</h1>
    </PageHeader>

    <Main title={title}>
      <div className="floaty-nav-wrapper">
        <nav className="floaty">
          <ul className="bulleted">
            <li><a href="#introduction">Introduction</a></li>

            <li><a href="#definitions">Definitions</a></li>

            <li><a href="#information-collection">Information Collection And Use</a></li>

            <li><a href="#use-of-data">Use of Data</a></li>

            <li><a href="#retention-of-data">Retention of Data</a></li>

            <li><a href="#transfer-of-data">Transfer of Data</a></li>

            <li><a href="#disclosure-of-data">Disclosure of Data</a></li>

            <li><a href="#security-of-data">Security of Data</a></li>

            <li><a href="#dnt-signals">"Do Not Track" Signals</a></li>

            <li><a href="#your-rights">Your Rights</a></li>

            <li><a href="#service-providers">Service Providers</a></li>

            <li><a href="#external-links">Links To Other Sites</a></li>

            <li><a href="#childrens-privacy">Children's Privacy</a></li>

            <li><a href="#changes">Changes To This Privacy Policy</a></li>

            <li><a href="#contact-us">Contact Us</a></li>
          </ul>
        </nav>

        <p><strong>Effective date:</strong> May 01, 2018</p>

        <section id="introduction">
          <p>Roll For Guild, Inc. ("us", "we", or "our") operates the <a href="https://rollforguild.com">rollforguild.com</a> website (the "Service").</p>

          <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

          <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms &amp; Conditions, accessible from <a href="//rollforguild.com/terms-and-conditions">https://rollforguild.com/terms-and-conditions</a>.</p>
        </section>

        <section id="definitions">
          <h2>Definitions</h2>

          <dl>
            <dt>Personal Data</dt>

            <dd>
              <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
            </dd>

            <dt>Usage Data</dt>

            <dd>
              <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            </dd>

            <dt>Cookies</dt>

            <dd>
              <p>Cookies are small pieces of data stored on a User’s device.</p>
            </dd>

            <dt>Data Controller</dt>

            <dd>
              <p>Data Controller means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.</p>

              <p>For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
            </dd>

            <dt>Data Processor (or Service Providers)</dt>

            <dd>
              <p>Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller.</p>

              <p>We may use the services of various Service Providers in order to process your data more effectively.</p>
            </dd>

            <dt>Data Subject</dt>

            <dd>
              <p>Data Subject is any living individual who is the subject of Personal Data.</p>
            </dd>

            <dt>User</dt>

            <dd>
              <p>The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
            </dd>
          </dl>
        </section>

        <section id="information-collection">
          <h2>Information Collection And Use</h2>

          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

          <h3>Types of Data Collected</h3>

          <dl>
            <dt>Personal Data</dt>

            <dd>
              <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>

              <ul className="bulleted">
                <li>Email address</li>

                <li>First name and last name</li>

                <li>Address, State, Province, ZIP/Postal code, City</li>

                <li>Cookies and Usage Data</li>
              </ul>

              <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</p>
            </dd>

            <dt>Usage Data</dt>

            <dd>
              <p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            </dd>

            <dt>Location Data</dt>

            <dd>
              <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.</p>

              <p>You can enable or disable location services when you use our Service at any time, through your device settings.</p>
            </dd>

            <dt>Tracking &amp; Cookies Data</dt>

            <dd>
              <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>

              <p>Cookies are files with containing a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>

              <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>

              <p>Examples of Cookies we use:</p>

              <ul>
                <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
                <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
              </ul>
            </dd>
          </dl>
        </section>

        <section id="use-of-data">
          <h2>Use of Data</h2>

          <p>Roll For Guild, Inc. uses the collected data for various purposes:</p>

          <ul className="bulleted">
            <li>To provide and maintain our Service</li>

            <li>To notify you about changes to our Service</li>

            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>

            <li>To provide customer support</li>

            <li>To gather analysis or valuable information so that we can improve our Service</li>

            <li>To monitor the usage of our Service</li>

            <li>To detect, prevent and address technical issues</li>

            <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
          </ul>
        </section>

        <section id="retention-of-data">
          <h2>Retention of Data</h2>

          <p>Roll For Guild, Inc. will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

          <p>Roll For Guild, Inc. will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
        </section>

        <section id="transfer-of-data">
          <h2>Transfer of Data</h2>

          <p>Your information, including Personal Data, may be transferred to &mdash; and maintained on &mdash; computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>

          <p>If you are located outside of the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.</p>

          <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>

          <p>Roll For Guild, Inc. will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
        </section>

        <section id="disclosure-of-data">
          <h2>Disclosure of Data</h2>

          <h3>Disclosure for Law Enforcement</h3>

          <p>Under certain circumstances, Roll For Guild, Inc. may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

          <h3>Legal Requirements</h3>

          <p>Roll For Guild, Inc. may disclose your Personal Data in the good faith belief that such action is necessary to:</p>

          <ul className="bulleted">
            <li>To comply with a legal obligation</li>

            <li>To protect and defend the rights or property of Roll For Guild, Inc.</li>

            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>

            <li>To protect the personal safety of users of the Service or the public</li>

            <li>To protect against legal liability</li>
          </ul>
        </section>

        <section id="security-of-data">
          <h2>Security Of Data</h2>

          <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
        </section>

        <section id="dnt-signals">
          <h2>"Do Not Track" Signals</h2>

          <p>We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>

          <p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
        </section>

        <section id="your-rights">
          <h2>Your Rights</h2>

          <p>Roll For Guild, Inc. aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>

          <p>Whenever made possible, you can update your Personal Data directly within your account settings section. If you are unable to change your Personal Data, please <a href="#contact-us">contact us</a> to make the required changes.</p>

          <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please <a href="#contact-us">contact us</a>.</p>

          <p>In certain circumstances, you have the right:</p>

          <ul className="bulleted">
            <li>To access and receive a copy of the Personal Data we hold about you</li>

            <li>To rectify any Personal Data held about you that is inaccurate</li>

            <li>To request the deletion of Personal Data held about you</li>
          </ul>

          <p>You have the right to data portability for the information you provide to Roll For Guild, Inc. You can request to obtain a copy of your Personal Data in a commonly used electronic format so that you can manage and move it.</p>

          <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
        </section>

        <section id="service-providers">
          <h2>Service Providers</h2>

          <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>

          <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

          <h3>Analytics</h3>

          <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

          <dl>
            <dt>Google Analytics</dt>

            <dd>
              <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>

              <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>

              <p>For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a href="http://www.google.com/intl/en/policies/privacy/">http://www.google.com/intl/en/policies/privacy/</a> </p>
            </dd>
          </dl>
        </section>

        <section id="external-links">
          <h2>Links To Other Sites</h2>

          <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>

          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        </section>

        <section id="childrens-privacy">
          <h2>Children's Privacy</h2>

          <p>Our Service does not address anyone under the age of 13 ("Children").</p>

          <p>We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please <a href="#contact-us">contact us</a>. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
        </section>

        <section id="changes">
          <h2>Changes To This Privacy Policy</h2>

          <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

          <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>

          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        </section>

        <section id="contact-us">
          <h2>Contact Us</h2>

          <p>If you have any questions about this Privacy Policy, please <a href="#contact-us">contact us</a>:</p>

          <ul>
            <li>By email: <a href="mailto:support@rollforguild.com">support@rollforguild.com</a></li>
            <li>By visiting our support website: <a href="https://support.rollforguild.com">support.rollforguild.com</a></li>
          </ul>
        </section>
      </div>
    </Main>
  </React.Fragment>
)





export default Page(PrivacyPolicy)
